from datetime import datetime
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import arabic_reshaper
from bidi.algorithm import get_display

REPORTS_DIR = Path(__file__).parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

# Register Arial Unicode for multi-language support
ARIAL_UNICODE = "/Library/Fonts/Arial Unicode.ttf"
pdfmetrics.registerFont(TTFont("ArialUnicode", ARIAL_UNICODE))

def _rtl(text: str) -> str:
    """Reshape and apply bidi algorithm so ReportLab renders Arabic/Urdu correctly."""
    return get_display(arabic_reshaper.reshape(text))

# A4 usable width: 21cm - 2*2cm margins = 17cm
PAGE_W = 17 * cm

RISK_COLORS = {
    "malignant":     colors.HexColor("#dc2626"),
    "pre-cancerous": colors.HexColor("#ea580c"),
    "benign":        colors.HexColor("#16a34a"),
}

TRIAGE_COLORS = {
    "Urgent": colors.HexColor("#dc2626"),
    "Medium": colors.HexColor("#ea580c"),
    "Low":    colors.HexColor("#16a34a"),
}

TRANSLATIONS = {
    "en": {
        "title": "Skin Lesion Analysis Report",
        "date": "Date",
        "disclaimer": "This report is generated by an AI tool and is not a medical diagnosis. Please consult a qualified dermatologist.",
        "prediction": "Prediction", "confidence": "Confidence", "risk": "Risk Level",
        "explanation": "What This Means", "triage": "Urgency", "triage_reason": "Reason",
        "next_steps": "What To Do Next", "dermatologists": "Nearby Dermatologists",
        "rating": "Rating", "address": "Address", "open": "Open now",
        "closed": "Closed", "unknown": "Unknown", "top3": "Top 3 Predictions",
        "generated": "Generated by SkinAI", "name": "Name", "status": "Status",
        "class": "Class", "rtl": False,
    },
    "ur": {
        "title": "جلدی زخم تجزیہ رپورٹ",
        "date": "تاریخ",
        "disclaimer": "یہ رپورٹ AI ٹول سے بنائی گئی ہے اور یہ طبی تشخیص نہیں ہے۔ براہ کرم ماہر ڈرماٹولوجسٹ سے رجوع کریں۔",
        "prediction": "تشخیص", "confidence": "اعتماد", "risk": "خطرے کی سطح",
        "explanation": "اس کا مطلب کیا ہے", "triage": "فوریت", "triage_reason": "وجہ",
        "next_steps": "آگے کیا کریں", "dermatologists": "قریبی ڈرماٹولوجسٹ",
        "rating": "درجہ بندی", "address": "پتہ", "open": "ابھی کھلا ہے",
        "closed": "بند", "unknown": "معلوم نہیں", "top3": "اعلی 3 پیشگوئیاں",
        "generated": "SkinAI سے تیار کردہ", "name": "نام", "status": "حالت",
        "class": "قسم", "rtl": True,
    },
    "ar": {
        "title": "تقرير تحليل الآفة الجلدية",
        "date": "التاريخ",
        "disclaimer": "هذا التقرير صادر عن أداة ذكاء اصطناعي وليس تشخيصاً طبياً. يرجى استشارة طبيب جلدية مؤهل.",
        "prediction": "التشخيص", "confidence": "الثقة", "risk": "مستوى الخطر",
        "explanation": "ماذا يعني هذا", "triage": "الاستعجال", "triage_reason": "السبب",
        "next_steps": "ماذا تفعل بعد ذلك", "dermatologists": "أطباء الجلدية القريبون",
        "rating": "التقييم", "address": "العنوان", "open": "مفتوح الآن",
        "closed": "مغلق", "unknown": "غير معروف", "top3": "أفضل 3 تنبؤات",
        "generated": "صادر عن SkinAI", "name": "الاسم", "status": "الحالة",
        "class": "الفئة", "rtl": True,
    },
}

HEADER_BG  = colors.HexColor("#1e293b")
ROW_ALT_BG = colors.HexColor("#f8fafc")
LABEL_BG   = colors.HexColor("#f1f5f9")
BORDER     = colors.HexColor("#e2e8f0")
TEXT_DARK  = colors.HexColor("#1e293b")
TEXT_MID   = colors.HexColor("#334155")
TEXT_LIGHT = colors.HexColor("#64748b")


def _make_styles(rtl=False):
    align = TA_RIGHT if rtl else TA_LEFT
    font  = "ArialUnicode" if rtl else "Helvetica"
    bold  = "ArialUnicode" if rtl else "Helvetica-Bold"

    return {
        "title":   ParagraphStyle("title",   fontName=bold,  fontSize=20, alignment=TA_CENTER,
                                   textColor=TEXT_DARK),
        "date":    ParagraphStyle("date",    fontName=font,  fontSize=9,  alignment=TA_CENTER,
                                   textColor=TEXT_LIGHT),
        "disc":    ParagraphStyle("disc",    fontName=font,  fontSize=8,  textColor=TEXT_LIGHT,
                                   backColor=ROW_ALT_BG, leftIndent=6, rightIndent=6,
                                   leading=13, alignment=align),
        "section": ParagraphStyle("section", fontName=bold,  fontSize=11, textColor=TEXT_DARK,
                                   spaceBefore=10, spaceAfter=5, alignment=align),
        "body":    ParagraphStyle("body",    fontName=font,  fontSize=10, textColor=TEXT_MID,
                                   leading=15, alignment=align),
        "cell":    ParagraphStyle("cell",    fontName=font,  fontSize=10, textColor=TEXT_MID,
                                   leading=14, alignment=align),
        "label":   ParagraphStyle("label",   fontName=bold,  fontSize=10, textColor=TEXT_DARK,
                                   leading=14, alignment=align),
        "header":  ParagraphStyle("header",  fontName=bold,  fontSize=10, textColor=colors.white,
                                   leading=14, alignment=align),
        "footer":  ParagraphStyle("footer",  fontName=font,  fontSize=8,  textColor=TEXT_LIGHT,
                                   alignment=TA_CENTER),
    }


def _base_table_style():
    return [
        ("FONTNAME",       (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE",       (0, 0), (-1, -1), 10),
        ("VALIGN",         (0, 0), (-1, -1), "TOP"),
        ("GRID",           (0, 0), (-1, -1), 0.4, BORDER),
        ("LEFTPADDING",    (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",   (0, 0), (-1, -1), 8),
        ("TOPPADDING",     (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 7),
    ]


def generate_pdf(
    prediction: dict,
    agent_output: dict,
    dermatologists: list,
    language: str = "en",
    image_path: str = None,
) -> str:
    t  = TRANSLATIONS.get(language, TRANSLATIONS["en"])
    rtl = t.get("rtl", False)
    s  = _make_styles(rtl=rtl)
    col1, col2 = 4 * cm, PAGE_W - 4 * cm

    def r(text: str) -> str:
        return _rtl(text) if rtl and text else text

    filename = f"skin_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = str(REPORTS_DIR / filename)

    doc = SimpleDocTemplate(
        filepath, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    story = []

    # Title + date as a single paragraph to avoid any overlap
    font_name = s["title"].fontName
    date_str  = datetime.now().strftime('%B %d, %Y')
    header_para = Paragraph(
        f'<font name="{font_name}" size="20" color="#1e293b"><b>{r(t["title"])}</b></font>'
        f'<br/>'
        f'<font name="{s["date"].fontName}" size="9" color="#64748b">{r(t["date"])}: {date_str}</font>',
        ParagraphStyle("header_combined", alignment=TA_CENTER, leading=28)
    )
    story.append(header_para)
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 0.3 * cm))

    # Disclaimer
    story.append(Paragraph(r(t["disclaimer"]), s["disc"]))
    story.append(Spacer(1, 0.5 * cm))

    # Prediction table
    risk_color  = RISK_COLORS.get(prediction.get("risk", "benign"), colors.grey)
    risk_style  = ParagraphStyle("risk", fontName=s["label"].fontName, fontSize=10,
                                  textColor=risk_color, leading=14)

    pred_data = [
        [Paragraph(r(t["prediction"]), s["label"]), Paragraph(prediction.get("full_name", ""), s["cell"])],
        [Paragraph(r(t["confidence"]),  s["label"]), Paragraph(f"{prediction.get('confidence', 0)}%", s["cell"])],
        [Paragraph(r(t["risk"]),        s["label"]), Paragraph(prediction.get("risk", "").upper(), risk_style)],
    ]
    pred_cmds = _base_table_style() + [
        ("BACKGROUND", (0, 0), (0, -1), LABEL_BG),
        ("BACKGROUND", (1, 1), (1, 1), ROW_ALT_BG),
    ]
    pred_table = Table(pred_data, colWidths=[col1, col2])
    pred_table.setStyle(TableStyle(pred_cmds))
    story.append(pred_table)
    story.append(Spacer(1, 0.5 * cm))

    # Top 3
    story.append(Paragraph(r(t["top3"]), s["section"]))
    num_w   = 1.5 * cm
    conf_w  = 3.5 * cm
    class_w = PAGE_W - num_w - conf_w

    top3_data = [[
        Paragraph("#",                s["header"]),
        Paragraph(r(t["class"]),      s["header"]),
        Paragraph(r(t["confidence"]), s["header"]),
    ]]
    for i, item in enumerate(prediction.get("top3", []), 1):
        top3_data.append([
            Paragraph(str(i),                   s["cell"]),
            Paragraph(item["full_name"],         s["cell"]),
            Paragraph(f"{item['confidence']}%",  s["cell"]),
        ])
    top3_cmds = _base_table_style() + [
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ("BACKGROUND", (0, 2), (-1, 2), ROW_ALT_BG),
    ]
    top3_table = Table(top3_data, colWidths=[num_w, class_w, conf_w])
    top3_table.setStyle(TableStyle(top3_cmds))
    story.append(top3_table)
    story.append(Spacer(1, 0.5 * cm))

    # Explanation
    story.append(Paragraph(r(t["explanation"]), s["section"]))
    story.append(Paragraph(r(agent_output.get("explanation", "")), s["body"]))
    story.append(Spacer(1, 0.5 * cm))

    # Triage
    triage       = agent_output.get("triage", {})
    triage_level = triage.get("level", "Medium")
    triage_color = TRIAGE_COLORS.get(triage_level, colors.grey)
    triage_style = ParagraphStyle("tl", fontName=s["label"].fontName, fontSize=10,
                                   textColor=triage_color, leading=14)

    story.append(Paragraph(r(t["triage"]), s["section"]))
    triage_data = [
        [Paragraph(r(t["triage"]),        s["label"]), Paragraph(triage_level,                          s["cell"])],
        [Paragraph(r(t["triage_reason"]), s["label"]), Paragraph(r(triage.get("reason", "")),            s["cell"])],
    ]
    triage_cmds = _base_table_style() + [
        ("BACKGROUND", (0, 0), (0, -1), LABEL_BG),
        ("BACKGROUND", (0, 1), (-1, 1), ROW_ALT_BG),
        ("TEXTCOLOR",  (1, 0), (1, 0),  triage_color),
        ("FONTNAME",   (1, 0), (1, 0),  "Helvetica-Bold"),
    ]
    triage_table = Table(triage_data, colWidths=[col1, col2])
    triage_table.setStyle(TableStyle(triage_cmds))
    story.append(triage_table)
    story.append(Spacer(1, 0.5 * cm))

    # Next steps
    story.append(Paragraph(r(t["next_steps"]), s["section"]))
    for i, step in enumerate(agent_output.get("next_steps", []), 1):
        story.append(Paragraph(r(f"{i}.  {step}"), s["body"]))
        story.append(Spacer(1, 0.15 * cm))

    # Dermatologists
    if dermatologists:
        story.append(Spacer(1, 0.3 * cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
        story.append(Spacer(1, 0.3 * cm))
        story.append(Paragraph(r(t["dermatologists"]), s["section"]))

        name_w   = 5 * cm
        rating_w = 2.2 * cm
        status_w = 2.5 * cm
        addr_w   = PAGE_W - name_w - rating_w - status_w

        derm_data = [[
            Paragraph(r(t["name"]),    s["header"]),
            Paragraph(r(t["address"]), s["header"]),
            Paragraph(r(t["rating"]),  s["header"]),
            Paragraph(r(t["status"]),  s["header"]),
        ]]
        for idx, d in enumerate(dermatologists):
            status = t["open"] if d.get("open_now") is True else (
                     t["closed"] if d.get("open_now") is False else t["unknown"])
            derm_data.append([
                Paragraph(d["name"],        s["cell"]),
                Paragraph(d["address"],     s["cell"]),
                Paragraph(str(d["rating"]), s["cell"]),
                Paragraph(r(status),        s["cell"]),
            ])
        derm_cmds = _base_table_style() + [
            ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
        ]
        for idx in range(1, len(derm_data)):
            if idx % 2 == 0:
                derm_cmds.append(("BACKGROUND", (0, idx), (-1, idx), ROW_ALT_BG))

        derm_table = Table(derm_data, colWidths=[name_w, addr_w, rating_w, status_w])
        derm_table.setStyle(TableStyle(derm_cmds))
        story.append(derm_table)

    # Footer
    story.append(Spacer(1, 0.8 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph(r(t["generated"]), s["footer"]))

    doc.build(story)
    return filename
